FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    git+https://github.com/osks/pylyskom.git \
    git+https://github.com/osks/httpkom.git

COPY seed.py /seed.py
COPY fixture.json /fixture.json

CMD ["python", "/seed.py", "--host", "lyskom-server", "--port", "4894", "/fixture.json"]
